service: proj-serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
  createUser:
    handler: Handlers/user.create
    events:
      - httpApi:
          path: /user
          method: post

plugins:
  - serverless-offline
